name: release

on:
  release:
    types: [created]

jobs:
  deploy:
    name: deploy to clojars
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 'latest'
          bb: 'latest'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
          key: clojure-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: clojure-deps-

      - name: Download dependencies
        run: clojure -P -M:test:build

      - name: Run tests
        run: bb test

      - name: Build and deploy to Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: bb ci:deploy
